// sitemap.xml, generated by walking /content plus the fixed public routes.
// A page cannot appear in the sitemap unless its markdown file exists, which is
// the whole point: it removes the drift that kills hand-maintained sitemaps.

const { listPages, isoDate } = require('./loader');

const ORIGIN = 'https://nivaria.app';

// Fixed, non-content URLs. Content URLs are appended from the file system.
const STATIC_URLS = [
  { loc: `${ORIGIN}/`, priority: '1.0' },
  { loc: `${ORIGIN}/terms`, priority: '0.3' },
  { loc: `${ORIGIN}/privacy`, priority: '0.3' },
  { loc: `${ORIGIN}/cookies`, priority: '0.3' },
];

function buildUrls() {
  const urls = STATIC_URLS.slice();
  for (const { meta } of listPages()) {
    if (typeof meta.slug !== 'string' || !meta.slug.startsWith('/')) continue;
    urls.push({
      loc: ORIGIN + meta.slug,
      lastmod: isoDate(meta.updated) || undefined,
      priority: '0.8',
    });
  }
  return urls;
}

function xmlEscape(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function buildSitemapXml() {
  const body = buildUrls().map(u => {
    const parts = [`<loc>${xmlEscape(u.loc)}</loc>`];
    if (u.lastmod) parts.push(`<lastmod>${u.lastmod}</lastmod>`);
    if (u.priority) parts.push(`<priority>${u.priority}</priority>`);
    return `  <url>${parts.join('')}</url>`;
  }).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`;
}

module.exports = { buildSitemapXml, buildUrls };
